version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:

  build-gateway-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-gateway-service/ && docker image build -t pixelgram/gateway-service:latest . && docker push pixelgram/gateway-service:latest

  build-image-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-image-service/ && docker image build -t pixelgram/image-service:latest . && docker push pixelgram/image-service:latest
    
  build-cloud-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-cloud-service/ && docker image build -t pixelgram/cloud-service:latest . && docker push pixelgram/cloud-service:latest
    
  build-user-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-user-service/ && docker image build -t pixelgram/user-service:latest . && docker push pixelgram/user-service:latest
    
  build-metadata-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-metadata-service/ && docker image build -t pixelgram/metadata-service:latest . && docker push pixelgram/metadata-service:latest

  build-react-ui:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-ui/ && docker image build -t pixelgram/pixelgram-ui:latest . && docker push pixelgram/pixelgram-ui:latest

workflows:
  build:
    jobs:
      - build-gateway-service
      - build-cloud-service
      - build-metadata-service
      - build-image-service
      - build-user-service
      - build-react-ui