version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:

  build-gateway-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-gateway-service/ && docker image build -t gateway-service:latest . && docker tag gateway-service:latest $DOCKER_USERNAME/gateway-service:latest
      - run: docker push $DOCKER_USERNAME/gateway-service:latest

  build-image-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-image-service/ && docker image build -t image-service:latest . && docker tag image-service:latest $DOCKER_USERNAME/image-service:latest
      - run: docker push $DOCKER_USERNAME/image-service:latest
    
  build-cloud-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-cloud-service/ && docker image build -t cloud-service:latest . && docker tag cloud-service:latest $DOCKER_USERNAME/cloud-service:latest
      - run: docker push $DOCKER_USERNAME/cloud-service:latest
    
  build-user-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-user-service/ && docker image build -t user-service:latest . && docker tag user-service:latest $DOCKER_USERNAME/user-service:latest
      - run: docker push $DOCKER_USERNAME/user-service:latest
    
  build-metadata-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-metadata-service/ && docker image build -t metadata-service:latest . && docker tag metadata-service:latest $DOCKER_USERNAME/metadata-service:latest
      - run: docker push $DOCKER_USERNAME/metadata-service:latest

  build-react-ui:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd pixelgram-ui/ && docker image build -t pixelgram-ui:latest . && docker tag pixelgram-ui:latest $DOCKER_USERNAME/pixelgram-ui:latest
      - run: docker push $DOCKER_USERNAME/pixelgram-ui:latest

workflows:
  build:
    jobs:
      - build-gateway-service
      - build-cloud-service
      - build-metadata-service
      - build-image-service
      - build-user-service
      - build-react-ui