FROM python:3.8.2-slim-buster
COPY . /docker-metadata-service

RUN adduser -D pixelgram
RUN chown pixelgram /docker-metadata-service
USER pixelgram

WORKDIR /docker-metadata-service

RUN pip install -r requirements.txt

EXPOSE 5006

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]