# Stage 1
FROM node:10-alpine as build-step
COPY . /pixelgram-ui
WORKDIR /pixelgram-ui
RUN npm install
RUN npm run build

# Stage 2
# FROM nginx:1.17.1-alpine
FROM nginxinc/nginx-unprivileged:1.18-alpine
COPY --from=build-step /pixelgram-ui/build /usr/share/nginx/html