FROM python:3.8.2-alpine
COPY . /docker-user-service

RUN adduser -D pixelgram
RUN chown pixelgram /docker-user-service
USER pixelgram

WORKDIR /docker-user-service

RUN touch data.db

RUN pip install -r requirements.txt

EXPOSE 5003

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]