pipeline {
    agent any
    // environment {

    // }
    stages {
        stage('Get source') {
            steps {
                script{
                    sh 'pwd'
                    checkout scm
                    deleteDir()
                    sh 'cp -rf /pixelgram-user-service UserService'
                    if(!fileExists("UserService/Dockerfile")) {
                        error('Dockerfile missing.')
                    }
                }
            }
        }
        stage('setup') {
            agent {  docker 'python:3.8.2' }
            steps {
                script{
                    dir('UserService'){
                        sh '. .env/bin/activate'
                        sh 'pip install --no-cache-dir  -r requriments.txt'
                    }
                }
            }

        }
        stage('Linting') {
            agent {  docker 'python:3.8.2' }
            steps {
                script {
                    dir('UserService'){
                        sh 'pylint **/*.py'
                    }
                } 
            }
        }
    }
}