# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import upload_service_pb2 as upload__service__pb2


class uploadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.uploadDataService = channel.unary_unary(
                '/uploadService/uploadDataService',
                request_serializer=upload__service__pb2.uploadDataRequest.SerializeToString,
                response_deserializer=upload__service__pb2.uploadDataResponse.FromString,
                )
        self.downloadDataService = channel.unary_unary(
                '/uploadService/downloadDataService',
                request_serializer=upload__service__pb2.uploadDataRequest.SerializeToString,
                response_deserializer=upload__service__pb2.downloadDataResponse.FromString,
                )


class uploadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def uploadDataService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def downloadDataService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_uploadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'uploadDataService': grpc.unary_unary_rpc_method_handler(
                    servicer.uploadDataService,
                    request_deserializer=upload__service__pb2.uploadDataRequest.FromString,
                    response_serializer=upload__service__pb2.uploadDataResponse.SerializeToString,
            ),
            'downloadDataService': grpc.unary_unary_rpc_method_handler(
                    servicer.downloadDataService,
                    request_deserializer=upload__service__pb2.uploadDataRequest.FromString,
                    response_serializer=upload__service__pb2.downloadDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uploadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class uploadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def uploadDataService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uploadService/uploadDataService',
            upload__service__pb2.uploadDataRequest.SerializeToString,
            upload__service__pb2.uploadDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def downloadDataService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uploadService/downloadDataService',
            upload__service__pb2.uploadDataRequest.SerializeToString,
            upload__service__pb2.downloadDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
