# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upload_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='upload_service.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14upload_service.proto\"b\n\x11uploadDataRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x11\n\timageName\x18\x02 \x01(\t\x12\x11\n\timageData\x18\x03 \x01(\x0c\x12\x17\n\x06\x66ormat\x18\x04 \x01(\x0e\x32\x07.Format\"&\n\x13\x64ownloadDataRequest\x12\x0f\n\x07imageId\x18\x01 \x01(\t\"5\n\x12uploadDataResponse\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0f\n\x07imageId\x18\x02 \x01(\t\":\n\x14\x64ownloadDataResponse\x12\x0f\n\x07imageId\x18\x01 \x01(\t\x12\x11\n\timageData\x18\x02 \x01(\x0c*%\n\x06\x46ormat\x12\x08\n\x04JPEG\x10\x00\x12\x07\n\x03PNG\x10\x01\x12\x08\n\x04WEBP\x10\x02\x32\x8f\x01\n\ruploadService\x12<\n\x11uploadDataService\x12\x12.uploadDataRequest\x1a\x13.uploadDataResponse\x12@\n\x13\x64ownloadDataService\x12\x12.uploadDataRequest\x1a\x15.downloadDataResponseB\x03\x90\x01\x01\x62\x06proto3'
)

_FORMAT = _descriptor.EnumDescriptor(
  name='Format',
  full_name='Format',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JPEG', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PNG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEBP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=279,
  serialized_end=316,
)
_sym_db.RegisterEnumDescriptor(_FORMAT)

Format = enum_type_wrapper.EnumTypeWrapper(_FORMAT)
JPEG = 0
PNG = 1
WEBP = 2



_UPLOADDATAREQUEST = _descriptor.Descriptor(
  name='uploadDataRequest',
  full_name='uploadDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='uploadDataRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageName', full_name='uploadDataRequest.imageName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageData', full_name='uploadDataRequest.imageData', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='format', full_name='uploadDataRequest.format', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=122,
)


_DOWNLOADDATAREQUEST = _descriptor.Descriptor(
  name='downloadDataRequest',
  full_name='downloadDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageId', full_name='downloadDataRequest.imageId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=162,
)


_UPLOADDATARESPONSE = _descriptor.Descriptor(
  name='uploadDataResponse',
  full_name='uploadDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='uploadDataResponse.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageId', full_name='uploadDataResponse.imageId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=217,
)


_DOWNLOADDATARESPONSE = _descriptor.Descriptor(
  name='downloadDataResponse',
  full_name='downloadDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageId', full_name='downloadDataResponse.imageId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageData', full_name='downloadDataResponse.imageData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=277,
)

_UPLOADDATAREQUEST.fields_by_name['format'].enum_type = _FORMAT
DESCRIPTOR.message_types_by_name['uploadDataRequest'] = _UPLOADDATAREQUEST
DESCRIPTOR.message_types_by_name['downloadDataRequest'] = _DOWNLOADDATAREQUEST
DESCRIPTOR.message_types_by_name['uploadDataResponse'] = _UPLOADDATARESPONSE
DESCRIPTOR.message_types_by_name['downloadDataResponse'] = _DOWNLOADDATARESPONSE
DESCRIPTOR.enum_types_by_name['Format'] = _FORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

uploadDataRequest = _reflection.GeneratedProtocolMessageType('uploadDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADDATAREQUEST,
  '__module__' : 'upload_service_pb2'
  # @@protoc_insertion_point(class_scope:uploadDataRequest)
  })
_sym_db.RegisterMessage(uploadDataRequest)

downloadDataRequest = _reflection.GeneratedProtocolMessageType('downloadDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADDATAREQUEST,
  '__module__' : 'upload_service_pb2'
  # @@protoc_insertion_point(class_scope:downloadDataRequest)
  })
_sym_db.RegisterMessage(downloadDataRequest)

uploadDataResponse = _reflection.GeneratedProtocolMessageType('uploadDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADDATARESPONSE,
  '__module__' : 'upload_service_pb2'
  # @@protoc_insertion_point(class_scope:uploadDataResponse)
  })
_sym_db.RegisterMessage(uploadDataResponse)

downloadDataResponse = _reflection.GeneratedProtocolMessageType('downloadDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADDATARESPONSE,
  '__module__' : 'upload_service_pb2'
  # @@protoc_insertion_point(class_scope:downloadDataResponse)
  })
_sym_db.RegisterMessage(downloadDataResponse)


DESCRIPTOR._options = None

_UPLOADSERVICE = _descriptor.ServiceDescriptor(
  name='uploadService',
  full_name='uploadService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=319,
  serialized_end=462,
  methods=[
  _descriptor.MethodDescriptor(
    name='uploadDataService',
    full_name='uploadService.uploadDataService',
    index=0,
    containing_service=None,
    input_type=_UPLOADDATAREQUEST,
    output_type=_UPLOADDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='downloadDataService',
    full_name='uploadService.downloadDataService',
    index=1,
    containing_service=None,
    input_type=_UPLOADDATAREQUEST,
    output_type=_DOWNLOADDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPLOADSERVICE)

DESCRIPTOR.services_by_name['uploadService'] = _UPLOADSERVICE

uploadService = service_reflection.GeneratedServiceType('uploadService', (_service.Service,), dict(
  DESCRIPTOR = _UPLOADSERVICE,
  __module__ = 'upload_service_pb2'
  ))

uploadService_Stub = service_reflection.GeneratedServiceStubType('uploadService_Stub', (uploadService,), dict(
  DESCRIPTOR = _UPLOADSERVICE,
  __module__ = 'upload_service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
