FROM python:3.8.2-alpine

COPY . /docker-cloud-service

RUN adduser -D pixelgram
RUN chown pixelgram /docker-cloud-service
USER pixelgram

WORKDIR /docker-cloud-service

RUN pip install -r requirements.txt

EXPOSE 5004

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]