def getEnvVar(String paramName){
    return sh (script: "grep -w '${paramName}' pixelgram-rabbitmq/project.properties|cut -d'=' -f2", returnStdout: true).trim();
}

def getTimeStamp(){
    return sh (script: "date +'%Y%m%d%H%M%S%N' | sed 's/[0-9][0-9][0-9][0-9][0-9][0-9]\$//g'", returnStdout: true).trim();
}

pipeline {

    agent any
	triggers {
        pollSCM '*/15 * * * *'
    }

    environment {
        GIT_COMMIT_SHORT_HASH = sh (script: "git rev-parse --short HEAD", returnStdout: true)
    }

    stages {
        stage('Init') {
            steps {
                script {
                    env.APP_NAME = getEnvVar('APP_NAME')
                    env.CURRENT_BRANCH = env.BRANCH_NAME
                    env.TIMESTAMP = getTimeStamp()
                    env.IMAGE_NAME = getEnvVar('IMAGE_NAME')
                    env.REPLICA = getEnvVar('REPLICA')
                    env.MAX_REPLICA = getEnvVar('MAX_REPLICA')
                    env.SERVICE_TYPE = getEnvVar('SERVICE_TYPE')
                    env.SERVICE_PATH = getEnvVar('SERVICE_PATH')
                    env.RELEASE_TAG = getEnvVar('RELEASE_TAG')
                    env.PROJECT_PATH = getEnvVar('PROJECT_PATH')
                    env.NODE_PORT = getEnvVar('NODE_PORT')
                    env.GITHUB_URL_YAML = "https://raw.githubusercontent.com/airavata-courses/PixelGram/${CURRENT_BRANCH}/${PROJECT_PATH}/kube.yaml"
                    env.GITHUB_URL_SH = "https://raw.githubusercontent.com/airavata-courses/PixelGram/${CURRENT_BRANCH}/${PROJECT_PATH}/process_file.sh"
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sshPublisher(
                        continueOnError: false, failOnError: true,
                        publishers: [
                            sshPublisherDesc(
                                configName: 'ssh_k8_master',
                                verbose: true,
                                transfers: [
                                    sshTransfer(
                                        execCommand: """
                                        [ ! -d "deployment_files" ] && mkdir deployment_files;
                                        cd deployment_files;
                                        rm -rf kube.yaml process_file.sh;
                                        wget ${GITHUB_URL_YAML}
                                        wget ${GITHUB_URL_SH}
                                        kubectl delete deployment,services,ingresses,horizontalpodautoscalers -l app=${APP_NAME};
                                        chmod +x process_file.sh;                           
                                        ./process_file.sh /home/centos/deployment_files ${APP_NAME} ${IMAGE_NAME}:${RELEASE_TAG} ${TIMESTAMP} ${REPLICA} ${MAX_REPLICA} ${SERVICE_TYPE} ${SERVICE_PATH} ${NODE_PORT};
                                        rm -rf *.bak*;
                                        cp -f kube.yaml ../k8-${APP_NAME}.yaml;
                                        cd ..;
                                        kubectl apply -f k8-${APP_NAME}.yaml;
                                        """
                                    )
                                ]
                            )
                        ]
                    )
                }
            }
        }

        stage('Deploy on IU') {
            steps {
                script {
                    sshPublisher(
                        continueOnError: false, failOnError: true,
                        publishers: [
                            sshPublisherDesc(
                                configName: 'ssh_k8_master_iu',
                                verbose: true,
                                transfers: [
                                    sshTransfer(
                                        execCommand: """
                                        [ ! -d "deployment_files" ] && mkdir deployment_files;
                                        cd deployment_files;
                                        rm -rf kube.yaml process_file.sh;
                                        wget ${GITHUB_URL_YAML}
                                        wget ${GITHUB_URL_SH}
                                        kubectl delete deployment,services,ingresses,horizontalpodautoscalers -l app=${APP_NAME};
                                        chmod +x process_file.sh;                           
                                        ./process_file.sh /home/centos/deployment_files ${APP_NAME} ${IMAGE_NAME}:${RELEASE_TAG} ${TIMESTAMP} ${REPLICA} ${MAX_REPLICA} ${SERVICE_TYPE} ${SERVICE_PATH} ${NODE_PORT};
                                        rm -rf *.bak*;
                                        cp -f kube.yaml ../k8-${APP_NAME}.yaml;
                                        cd ..;
                                        kubectl apply -f k8-${APP_NAME}.yaml;
                                        """
                                    )
                                ]
                            )
                        ]
                    )
                }
            }
        }
    }
}